import { Inter } from "next/font/google";
import { PHProvider } from './providers'
import "./globals.css";
import Banner from './banner';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PHProvider>
        <body className={inter.className}>
          {children}
          <Banner />
        </body>
      </PHProvider>
    </html>
  )
}